config/routes.rb
Rails.application.routes.draw do

  resources :pictures
  root 'pictures#index'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  validates :title, presence: true
  validates :image_url, presence: true
  mount_uploader :image_url, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pictures
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  mount_uploader :avatar, AvatarUploader

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_actionで下で定義したメソッドを実行
  # 
  before_action :configure_permitted_parameters, if: :devise_controller?

  # 新規登録とアカウント更新の際に、パラメータにnameが入るようにする
  PERMISSIBLE_ATTRIBUTES = %i(name avatar_cache)

  protected

    #deviseのストロングパラメーターにカラム追加するメソッドを定義
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @user = current_user
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:title, :image_url, :image_url_cache)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def profile_img(user)
    return image_tag(user.avatar, alt: user.name) if user.avatar?

    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: user.name)
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>大課題2インスタClone</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'shared/navbar' %>

    <p class="flash text-center"><%= notice %><%= alert %></p>

    <!-- ログイン・ログアウト操作 -->

    <%= yield %>

    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% @picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <% if @picture.image_url? %>
    <div class="thumbnail">
      <%= image_tag @picture.image_url %>
    </div>
  <% end %><br>
  <%= f.label :image_url %><br>
  <%= f.file_field :image_url %>
  <%= f.hidden_field :image_url_cache %>

  <div class="field">
    <%= f.submit '投稿', class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<div class="container">

  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2">
      <!-- TWEET WRAPPER START -->
      <div class="twt-wrapper">
        <div class="">
          <div class="panel-heading">画像編集</div>
          <div class="panel-body">
            <%= render 'form' %>
            <%= link_to '詳細', @picture %> |
            <%= link_to '戻る', pictures_path %>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
      <!-- TWEET WRAPPER END -->
    </div>
  </div>

</div>

app/views/pictures/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2">
      <!-- TWEET WRAPPER START -->
      <div class="twt-wrapper">
          <div class=""><%= @user.name %>さんのタイムライン</div>
          <div class="">
            <ul class="media-list">
              <%= link_to '新規画像投稿', new_picture_path, class: "btn btn-block btn-default" %>
            </ul>

            <ul class="media-list">
              <% @pictures.each do |picture| %>
                <li class="media">
                  <div class="timeline-header">
                    <%= profile_img(picture.user) if profile_img(picture.user) %>
                    <strong class="text-success">@<%= picture.user.name %></strong>
                  </div>
                  <div class="media-body">
                    <span class="text-muted pull-right">
                    </span>
                    <p><%= image_tag(picture.image_url, class: 'timeline-picture') %></p>
                  </div>
                </li>
                <%= link_to '詳細', picture, class: '' %>
                <%= link_to '編集', edit_picture_path(picture), class: '' %>
                <%= link_to '削除', picture, method: :delete, data: { confirm: 'Are you sure?' }, class: '' %>
              <% end %>
            </ul>
          </div>
      </div>
      <!-- TWEET WRAPPER END -->
    </div>
  </div>
</div>

app/views/pictures/new.html.erb
<div class="container">

  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2">
      <!-- TWEET WRAPPER START -->
      <div class="twt-wrapper">
        <div class="panel panel-default">
          <div class="panel-heading">
            新規投稿
          </div>
          <div class="panel-body">
            <%= render 'form' %>
            <%= link_to '戻る', pictures_path %>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
      <!-- TWEET WRAPPER END -->
    </div>
  </div>

</div>

app/views/pictures/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1">
      <!-- TWEET WRAPPER START -->
      <div class="twt-wrapper">
        <div class="">
          <div class="panel-heading">
            画像詳細
          </div>
          <div class="panel-body">
            <ul class="media-list">
              <p>
              <strong>Title:</strong>
              <%= @picture.title %>
              </p>

              <p>
              <strong>Image:</strong>
              <% if @picture.image_url? %>
                <div class="thumbnail">
                  <%= image_tag @picture.image_url %>
                </div>
              <% end %>
              </p> 
            </ul>
            <%= link_to '編集', edit_picture_path(@picture) %> |
            <%= link_to '戻る', pictures_path %>
          </div>
        </div>
      </div>
      <!-- TWEET WRAPPER END -->
    </div>
  </div>





</div>

app/views/shared/_footer.html.erb
<!-- GOOGLE ADD SECTION START -->
<div id="add-div-main">
  <link href="http://designbootstrap.com/track/add-style.css" rel="stylesheet" />
  <div class="add-wrapper-db">
    <div class="container">
    </div>
  </div>
</div>
<!-- GOOGLE ADD SECTION END -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'top', pictures_path, class: 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right ">
        <% if user_signed_in? %>
          <li><%= link_to 'ピクチャー', pictures_path %></li>
          <li><%= link_to 'マイページ', edit_user_registration_path %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path  %></li>
          <li><%= link_to 'サインアップ', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>

  </div>
</div>
<!-- NAVBAR CODE END -->